# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a0807035b55d6bd0c92349cc875a1f1d0d35046434d21834f92a772a2d1981ba726cbd1944fdc6f76dcd46498993bdfe477af4bae70dd83fdc5a8884362da37

test:
  secret_key_base: 9a25398e83b25b99e67adb98c8223b1525150d4a08381b094db3e2d12de315b01c0c27d9627363f0f8357ea4a32828898e9315e35ae797fad63add084dc8983d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
